### ISSUE TITLE
Could you offer a runable bash script?

### ISSUE THREAD

**Issue by fcdhd** [benedettaliberatori/T3AL#11]
I'm quite interested in your remarkable work!
However, here are some problem with bash script, I don't konw how to fix some parameters.
Could you offer a runable bash script with all parameters writed? Thank you very much.

**Comment by benedettaliberatori** [comment]
Hi, thank you for your interest in our work!

We already provide bash scripts for running evaluations. You can choose between those in the [configs](https://github.com/benedettaliberatori/T3AL/tree/main/configs/experiment) and run it as detailed in the README in the evaluation section. 

Let me know if you need any further assistance!
