### ISSUE TITLE
Inquiry About video_path?

### ISSUE THREAD

**Issue by fcdhd** [benedettaliberatori/T3AL#12]
Dear Author,

Thank you for your outstanding work on the paper titled "Test-Time Zero-Shot Temporal Action Localization". I am currently trying to replicate the experiments. However, I was confused about video_path, what should I put in this video_path? Activitynet and THUMOS's videos?

![image](https://github.com/user-attachments/assets/4d5dd7ae-ac51-4943-8731-e19ce7ef0026)

**Comment by fcdhd** [comment]
Could you offer download link, thank you very much?

**Comment by benedettaliberatori** [comment]
Hi, thank you again for your interest in our work!

That `/path/to/` is a placeholder, you can download videos or/and features depending on what you prefer to use, and change the paths according to the paths on your machine. In the README you will find links to download pre-extracted features. 

Let me know if you need any further assistance!

**Comment by znithx** [comment]
if i want to replicate the experiments you mentioned in your paper, how should i set the video_path?  
And then i want to know the link of Captions in README should be set in where?

**Comment by benedettaliberatori** [comment]
Please see the reply in #23

**Comment by znithx** [comment]
thank you！
