### ISSUE TITLE
Inquiry About predicted.csv?

### ISSUE THREAD

**Issue by fcdhd** [benedettaliberatori/T3AL#13]
Dear Author,

Thank you for your outstanding work. I am currently trying to reproduce the experiments.
However, predicted.csv is empty after training, it seems like missing 'label', KeyError: 'label'.
Thank you for your time and assistance. I look forward to your reply.

**Comment by adabrh** [comment]
Hey.
i am facing same issue of missing 'label', KeyError: 'label'.
Can you kindly tell me how did you resolve it?
It will be very helpfull.
Thank You.

**Comment by znithx** [comment]
i am facing same issue of missing 'label', KeyError: 'label'.|
Do you solve it?
