### ISSUE TITLE
Inquiry about fps of THUMOS and ActivityNet？

### ISSUE THREAD

**Issue by fcdhd** [benedettaliberatori/T3AL#14]
Dear Author,

Thank you for your outstanding work. I am currently trying to reproduce the experiments.
However, I can't get fps with opencv, could you tell me the fps of THUMOS and ActivityNet.
Thank you for your time and assistance. I look forward to your reply.

**Comment by benedettaliberatori** [comment]
Hi, thank you again for your interest in our work!

We decode videos at the original fps, so we use the `get_video_fps` function to get the number from videos directly. If you do not want to download videos to get these numbers, consider that most of the videos have **30** fps, so you can use this number as a proxy for the whole dataset. Yet, I advise you to download the dataset in video format and use opencv to get original fps as well if you can. 
Let me know if I can help you further.

**Comment by fcdhd** [comment]
I got it, thank you!
