### ISSUE TITLE
Inquiry about model.split？

### ISSUE THREAD

**Issue by fcdhd** [benedettaliberatori/T3AL#15]
Dear Author,

Thank you for your outstanding work. I am currently trying to reproduce the experiments.

However, I am confused about the meaning of 'model.split', what's the different between model.split = 0,1,2,3,4,5,6,7,8,9.
![image](https://github.com/user-attachments/assets/a563ab97-1f44-48ec-9a09-21cb7b6043b8)

Thank you for your time and assistance. I look forward to your reply.

**Comment by benedettaliberatori** [comment]
Hi, thank you again for your interest in our work!

The evaluation setting was introduced in the paper [Prompting Visual-Language Models for Efficient
Video Understanding](https://arxiv.org/pdf/2112.04478), as the authors explain in: 
 
![image](https://github.com/user-attachments/assets/a87504a9-b138-46ff-9f6e-14cae7edd053)

The final results are therefore averaged over 10 runs, each with different train/test categories splitting. 
I hope this clears your doubts.

**Comment by fcdhd** [comment]
Thank you very much!!! It is very helpful.
