### ISSUE TITLE
requirements.txt not found

### ISSUE THREAD

**Issue by LanchJL** [benedettaliberatori/T3AL#5]
I am grateful to the author for generously sharing the code related to this valuable work.	However, I was unable to locate the requirements.txt file, and I have concerns about the potential impact of varying environment configurations on the reproducibility of the results. May I ask if the author has any intention of uploading this file, or provide guidance on where I might have overlooked it.

**Comment by benedettaliberatori** [comment]
Hi, thank you for your interest in our work! 
I have added it in the repo.
