### ISSUE TITLE
Model file loading problem

### ISSUE THREAD

**Issue by ZWXCV** [benedettaliberatori/T3AL#8]
Hello author, thank you very much for your work. At present, I encountered a problem when using the code you provided, that is, I could not connect to huggingface to download the model file, so I downloaded the model file to the local, but I did not know where to put it in the project, or I hope the author can give me a reply. I am very grateful and looking forward to your reply.

Error example:

huggingface_hub.errors.LocalEntryNotFoundError:  An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache.  Please check your connection and try again or make sure your Internet connection is on.

**Comment by benedettaliberatori** [comment]
Hi, thank you for reaching out!

If you're only able to download the model files manually, you can place them in the default cache directory that Hugging Face uses. On my machine it is under `~/.cache/huggingface/hub/`. 

Specifically, I have a directory named `~/.cache/huggingface/hub/models--laion--mscoco_finetuned_CoCa-ViT-L-14-laion2B-s13B-b90k`, where the model files are stored. Does this work for you? 

Alternatively, if you want to load the model directly from the downloaded checkpoints, you can modify the code to reference the local path. This is the part you should modify:

```
self.model, _, _ = open_clip.create_model_and_transforms(
            model_name="coca_ViT-L-14", pretrained="mscoco_finetuned_laion2B-s13B-b90k"
        ) 
```

Let me know if you need any further assistance!
