### ISSUE TITLE
Inquiry About Dataset THUMOS14

### ISSUE THREAD

**Issue by Geneam** [benedettaliberatori/T3AL#9]
Dear Author,

Thank you for your outstanding work on the paper titled "Test-Time Zero-Shot Temporal Action Localization". I am currently trying to replicate the experiments. However, I was unable to find the specific version of the THUMOS14 mentioned in the paper on https://www.crcv.ucf.edu/THUMOS14/download.html.
![image](https://github.com/user-attachments/assets/aea879b9-3196-4658-ba9d-ffc9f76e7c6b)

Could you kindly provide more information about the dataset used, or guide me on how to access the version you referenced in your work?

Thank you for your time and assistance. I look forward to your reply.

**Comment by benedettaliberatori** [comment]
Hi, thank you for your interest in our work!

The [link](https://www.crcv.ucf.edu/THUMOS14/download.html) you provide contains access to both UCF101 and THUMOS14 datasets. You can see that there are _Temporal annotations of actions_ for videos in the validation and test data subsets. 
You can download the videos and the temporal annotations, and then keep only those videos with temporal annotations. This way, you can find the 413 videos with temporal action localization annotations. 

Let me know if you need any further assistance!
